dist: xenial
language: python
python:
- '3.6'

install:
- pip install -U -r requirements-dev.txt

script:
- flake8 puzzle tests
- black --target-version py36 --line-length 79 --check puzzle tests
- pytest tests/ --cov-report xml --cov=puzzle

after_success:
- codecov -t "$CODECOV_TOKEN"
